version: "3.7"

services:
  whoami:
    image: containous/whoami:v1.3.0
    env_file:
      - .env
    networks:
      - orlando-internal
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      # Generate route for secure http 
      - "traefik.http.routers.whoami-secured.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whoami-secured.entrypoints=websecure"
      - "traefik.http.routers.whoami-secured.tls=true"
      # connect to leresolver (Let's Encrypt)
      # - "traefik.http.routers.whoami-secured.tls.certresolver=leresolver"
      # Generate route for insecure http; redirect via middleware.secure.header
      - "traefik.http.routers.whoami.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=web"
      # Enforce a minimum version of the TLS protocol:  ToDo: TLS 1.2 or 1.3? 
      #- "traefik.tls.options.default.minVersion=VersionTLS13"
      # Connect route to TLS options ToDo: test
      - "traefik.http.routers.whoami-secured.tls.options=default@file" 
      # Apply middleware "secure" to entrypoints
      - "traefik.http.routers.whoami.middlewares=secure@file"
      - "traefik.http.routers.whoami-secured.middlewares=secure@file"

networks:
  orlando-internal:
